[package]
name = "bbreakout"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto="thin"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[dependencies]
bevy = "0.16.1"
